/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dialogos;

import java.awt.Color;
import javax.swing.JColorChooser;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author uo292393
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        
        DF = new JFileChooser();
        DPP = new DatosPersonales();
     
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TFColor = new javax.swing.JTextField();
        BFrente = new javax.swing.JButton();
        Bborrar = new javax.swing.JButton();
        PColor = new javax.swing.JPanel();
        Bcolor = new javax.swing.JButton();
        BGuardar = new javax.swing.JButton();
        LFichero = new javax.swing.JLabel();
        BDatosPersonales = new javax.swing.JButton();
        LDatosPersonales = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setText("Color");

        BFrente.setText("Frente");
        BFrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFrenteActionPerformed(evt);
            }
        });

        Bborrar.setText("Borrar");
        Bborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BborrarActionPerformed(evt);
            }
        });

        PColor.setBackground(new java.awt.Color(255, 255, 255));

        Bcolor.setText("Color");
        Bcolor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcolorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PColorLayout = new javax.swing.GroupLayout(PColor);
        PColor.setLayout(PColorLayout);
        PColorLayout.setHorizontalGroup(
            PColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PColorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Bcolor)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        PColorLayout.setVerticalGroup(
            PColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PColorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Bcolor)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        BGuardar.setBackground(new java.awt.Color(153, 255, 255));
        BGuardar.setText("Guardar");
        BGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGuardarActionPerformed(evt);
            }
        });

        LFichero.setBackground(new java.awt.Color(153, 255, 255));
        LFichero.setOpaque(true);

        BDatosPersonales.setBackground(new java.awt.Color(153, 255, 102));
        BDatosPersonales.setText("Datos personales");
        BDatosPersonales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDatosPersonalesActionPerformed(evt);
            }
        });

        LDatosPersonales.setBackground(new java.awt.Color(102, 255, 102));
        LDatosPersonales.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Bborrar)
                        .addGap(0, 397, Short.MAX_VALUE))
                    .addComponent(LFichero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TFColor, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(BGuardar)
                                .addComponent(PColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BFrente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 260, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BDatosPersonales)
                                    .addComponent(LDatosPersonales, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TFColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BFrente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Bborrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BDatosPersonales)
                        .addGap(14, 14, 14)
                        .addComponent(LDatosPersonales, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LFichero, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BFrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFrenteActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"El color de frente será "+TFColor.getText(),"Color de frente",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_BFrenteActionPerformed

    private void BborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BborrarActionPerformed
        // TODO add your handling code here:
       int ret= JOptionPane.showConfirmDialog(null,"Se borrará el color "+TFColor.getText(),"Borrar color",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
       if(ret == JOptionPane.YES_OPTION){
           TFColor.setText("");
       }
    }//GEN-LAST:event_BborrarActionPerformed

    private void BcolorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcolorActionPerformed
        // TODO add your handling code here:
        
        Color c = JColorChooser.showDialog(null, "Color del panel", PColor.getBackground());
        if(c!=null){
            PColor.setBackground(c);
        }
                
    }//GEN-LAST:event_BcolorActionPerformed

    private void BGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGuardarActionPerformed
        // TODO add your handling code here:
        
        int ret = DF.showSaveDialog(null);
        if(ret == JFileChooser.APPROVE_OPTION){
            LFichero.setText(DF.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_BGuardarActionPerformed

    private void BDatosPersonalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDatosPersonalesActionPerformed
        // TODO add your handling code here:
        boolean POK = DPP.showDialog(LDatosPersonales.getText());
        if(POK){
            LDatosPersonales.setText(DPP.getNombre());
        }
        
        
    }//GEN-LAST:event_BDatosPersonalesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
   JFileChooser DF  ;//Paso 1 crear referencia
   DatosPersonales DPP;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BDatosPersonales;
    private javax.swing.JButton BFrente;
    private javax.swing.JButton BGuardar;
    private javax.swing.JButton Bborrar;
    private javax.swing.JButton Bcolor;
    private javax.swing.JLabel LDatosPersonales;
    private javax.swing.JLabel LFichero;
    private javax.swing.JPanel PColor;
    private javax.swing.JTextField TFColor;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
