/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pintado;

/**
 *
 * @author uo266600
 */
public class Pintado extends javax.swing.JFrame {

    /**
     * Creates new form Pintado
     */
    public Pintado() {
        initComponents();
        paintPanel=(PaintPanel)PPaint;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PPaint = new PaintPanel();
        TFTexto = new TextFieldSub();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        PPaint.setBackground(new java.awt.Color(255, 255, 255));
        PPaint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PPaintMousePressed(evt);
            }
        });

        TFTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFTextoActionPerformed(evt);
            }
        });
        TFTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TFTextoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout PPaintLayout = new javax.swing.GroupLayout(PPaint);
        PPaint.setLayout(PPaintLayout);
        PPaintLayout.setHorizontalGroup(
            PPaintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PPaintLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(TFTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(398, Short.MAX_VALUE))
        );
        PPaintLayout.setVerticalGroup(
            PPaintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PPaintLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(TFTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(300, Short.MAX_VALUE))
        );

        getContentPane().add(PPaint);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PPaintMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PPaintMousePressed
        // TODO add your handling code here:
        int px=evt.getX();
        int py=evt.getY();
        paintPanel.setP(px, py);
        paintPanel.repaint();
    }//GEN-LAST:event_PPaintMousePressed

    private void TFTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFTextoActionPerformed

    private void TFTextoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFTextoKeyReleased
        // TODO add your handling code here:
        paintPanel.setT(TFTexto.getText());
        paintPanel.repaint();
    }//GEN-LAST:event_TFTextoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pintado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pintado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pintado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pintado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pintado().setVisible(true);
            }
        });
    }
    
    private TextFieldSub textField;
    private PaintPanel paintPanel;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PPaint;
    private javax.swing.JTextField TFTexto;
    // End of variables declaration//GEN-END:variables
}
